server:
  port: 9000

spring:
  application:
    name: xtrade-auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/xtrade_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  internal-api-key: xtrade-int-2026-Ud8VwJ7sR4qPz2nK9mT6bY3aLx5cE1h
  security:
    issuer: http://localhost:9000

  cors:
    allowed-origins:
      http://127.0.0.1:3000, http://localhost:3000